apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y1gm1kf6x-nodejs
  janus-idp.io/tekton: y1gm1kf6x-nodejs
  backstage.io/kubernetes-id: y1gm1kf6x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y1gm1kf6x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
